# Generated by Django 4.2.23 on 2025-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='Mentor Name', max_length=200),
        ),
    ]
